import { FiseContext, FiseRules } from "../types.js";

/**
 * FISE Builder Instance - Fluent API for creating FISE rules.
 * Focuses on the 3 security points: offset, encodeLength, decodeLength.
 */
export class FiseBuilderInstance {
    private offsetFn?: (cipherText: string, ctx: FiseContext) => number;
    private encodeLengthFn?: (len: number, ctx: FiseContext) => string;
    private decodeLengthFn?: (encoded: string, ctx: FiseContext) => number;
    private saltRange?: { min: number; max: number };
    private extractSaltFn?: (envelope: string, saltLen: number, ctx: FiseContext) => string;
    private stripSaltFn?: (envelope: string, saltLen: number, ctx: FiseContext) => string;

    /**
     * Set the offset function (REQUIRED - Security Point #1)
     * @example .withOffset((c, ctx) => (c.length * 7 + (ctx.timestampMinutes % 11)) % c.length)
     */
    withOffset(fn: (cipherText: string, ctx: FiseContext) => number): this {
        this.offsetFn = fn;
        return this;
    }

    /**
     * Set encodeLength function (REQUIRED - Security Point #2)
     * @example .withEncodeLength((len) => len.toString(36).padStart(2, "0"))
     */
    withEncodeLength(fn: (len: number, ctx: FiseContext) => string): this {
        this.encodeLengthFn = fn;
        return this;
    }

    /**
     * Set decodeLength function (REQUIRED - Security Point #3)
     * @example .withDecodeLength((encoded) => parseInt(encoded, 36))
     */
    withDecodeLength(fn: (encoded: string, ctx: FiseContext) => number): this {
        this.decodeLengthFn = fn;
        return this;
    }




    /**
     * Set salt range (optional, default: 10-99)
     * @example .withSaltRange(10, 99)
     */
    withSaltRange(min: number = 10, max: number = 99): this {
        this.saltRange = { min, max };
        return this;
    }

    /**
     * Set custom salt extraction (optional, default: tail-based)
     * @example .withHeadSalt()
     */
    withHeadSalt(): this {
        this.extractSaltFn = (envelope, saltLen) => envelope.slice(0, saltLen);
        this.stripSaltFn = (envelope, saltLen) => envelope.slice(saltLen);
        return this;
    }

    /**
     * Set custom salt extraction functions (optional)
     * @example .withCustomSaltExtraction(extract, strip)
     */
    withCustomSaltExtraction(
        extract: (envelope: string, saltLen: number, ctx: FiseContext) => string,
        strip: (envelope: string, saltLen: number, ctx: FiseContext) => string
    ): this {
        this.extractSaltFn = extract;
        this.stripSaltFn = strip;
        return this;
    }

    /**
     * Build the FiseRules object
     * Only includes the 3 security points + optional overrides.
     * Everything else is auto-generated by normalizeFiseRules.
     */
    build(): FiseRules {
        if (!this.offsetFn) {
            throw new Error("FISE FiseBuilderInstance: withOffset() is required");
        }
        if (!this.encodeLengthFn || !this.decodeLengthFn) {
            // Default to base36 if not specified
            this.encodeLengthFn = (len) => len.toString(36).padStart(2, "0");
            this.decodeLengthFn = (encoded) => parseInt(encoded, 36);
        }

        const rules: FiseRules = {
            offset: this.offsetFn!,
            encodeLength: this.encodeLengthFn!,
            decodeLength: this.decodeLengthFn!
        };

        if (this.saltRange) {
            rules.saltRange = this.saltRange;
        }

        if (this.extractSaltFn && this.stripSaltFn) {
            rules.extractSalt = this.extractSaltFn;
            rules.stripSalt = this.stripSaltFn;
        }

        return rules;
    }

}
